export const SWAP_BOUNS_WALLET_KEY = 'BW000';
export const SWAP_COPY_WALLET_KEY = 'COPY';
export const SWAP_GRID_WALLET_KEY = 'GRID';
export const SWAP_DEFAULT_WALLET_KEY = 'W001';

export const SWAP_WALLET_ALIAS = {
  [SWAP_BOUNS_WALLET_KEY]: '体验金账户',
  [SWAP_COPY_WALLET_KEY]: '跟单账户',
  [SWAP_GRID_WALLET_KEY]: 'GRID',
  [SWAP_DEFAULT_WALLET_KEY]: 'U本位账户'
}

export enum WalletKey {
  BOUNS = SWAP_BOUNS_WALLET_KEY,
  COPY = SWAP_COPY_WALLET_KEY,
  GRID = SWAP_GRID_WALLET_KEY,
  SWAP_U = SWAP_DEFAULT_WALLET_KEY
}
