import EventEmitter from 'events';

export const kChartEmitter = new (class extends EventEmitter {
  public K_CHART_FULL_SCREEN = 'K_CHART_FULL_SCREEN'; // 全屏

  public K_CHART_INDICATOR_TRADINGVIEW = 'K_CHART_INDICATOR_TRADINGVIEW'; // 指标
  public K_CHART_INDICATOR_KLINE = 'K_CHART_INDICATOR_KLINE'; // 指标

  public K_CHART_SCREENSHOT = 'K_CHART_SCREENSHOT'; // 截图
  public K_CHART_SCREENSHOT_TRADINGVIEW = 'K_CHART_SCREENSHOT_TRADINGVIEW'; // 截图

  public K_CHART_SEARCH_SYMBOL = 'K_CHART_SEARCH_SYMBOL'; // 搜索
  public K_CHART_SEARCH_SYMBOL_TRADINGVIEW = 'K_CHART_SEARCH_SYMBOL_TRADINGVIEW'; // 搜索

  public K_CHART_SWITCH_CHART_TYPE = 'K_CHART_SWITCH_CHART_TYPE'; // 切换图表类型

  public K_CHART_SWITCH_COLOR = 'K_CHART_SWITCH_COLOR'; // 切换涨跌颜色

  public K_CHART_CLICK_CROSSHAIR_PRICE = 'K_CHART_CLICK_CROSSHAIR_PRICE'; // 获取图标坐标当前价格
})();
